### ISSUE TITLE
Download link taken down

### ISSUE THREAD

**Issue by Glenta** [YTLitePlus/ytliteplus.github.io#1]
The direct download link for the IPA no longer works, probably got DMCAed by Google, going forward do you plan to use another file hosting service or just no longer provide IPAs?

If you plan to move to another hosting service you could use [Catbox](https://catbox.moe/), they provide direct download URLs so its very easy to add an "Open in Altstore" button aswell. However, if you want to follow their ToS they state:
> You own, or undertake that you are authorised to use, any intellectual property in any data you store on, use, download, upload, share, access, transmit or otherwise make available to or from, our Services.

If you don't care about direct links to the IPA you could use [GoFile](https://gofile.io/) as their copyright policy is lax.

**Comment by Balackburn** [comment]
Yes it got DMCAed
